## Directories
## Data directory
data:
    data_raw: "../data/raw"
    data_clean: "../data/clean"
    results:
        logistic_regression: "../data/results/logistic_regression"

results:
    graphs: "../results/graphs"
    tables: "../results/tables"

logging:
    logistic_regression: "../logs/logistic_regression_logs.log"

models:
    logistic_regression:
        preprocessor: "../models/logistic_regression/logistic_regression_preprocessor.pkl"
        params:  "../models/logistic_regression/logistic_regression_params.pkl"
        model:   "../models/logistic_regression/logistic_regression_model.pkl"
    random_forest:
        preprocessor: "../models/logistic_regression/random_forest_preprocessor.pkl"
        params:  "../models/random_forest/random_forest_params.pkl"
        model:   "../models/random_forest/random_forest_model.pkl"
    xg_boost:
        preprocessor: "../models/logistic_regression/xgboost_preprocessor.pkl"
        params:  "../models/xgboost/xgboost_params.pkl"
        model:   "../models/xgboost/xgboost_model.pkl"


## Colors:
colors:
    rojo: "#ec0c2b"
    teal: "#1c9c9c"
    azul: "#043464"
    gris: "#BFBFBF"
