## Directories
## Data directory
data:
    data_raw: "../data/raw"
    data_clean: "../data/clean"

results:
    graphs: "../results/graphs"
    tables: "../results/tables"

logging:
    training: "../logs/training_logs.log"

models:
    logistic_regression:
        params:  "../models/logistic_regression/logistic_regression_params.pkl"
        model:   "../models/logistic_regression/logistic_regression_model.pkl"
    random_forest:
        params:  "../models/random_forest/random_forest_params.pkl"
        model:   "../models/random_forest/random_forest_model.pkl"
    xg_boost:
        params:  "../models/xgboost/xgboost_params.pkl"
        model:   "../models/xgboost/xgboost_model.pkl"


## Colors:
colors:
    rojo: "#ec0c2b"
    teal: "#1c9c9c"
    azul: "#043464"
    gris: "#BFBFBF"
